### PR TITLE
docs: update install instructions to match homepage

### PR DESCRIPTION
**Pull request by balupton**
As the current URL returns a 404:

```
> echo https://tea.xyz/$(uname)/$(uname -m)
https://tea.xyz/Darwin/arm64
> curl https://tea.xyz/Darwin/arm64
<html><head><meta http-equiv='refresh' content='0; URL=https://tea.xyz/tea-darwin+aarch64'></head></html>⏎   
```

### CODE REVIEW

**Comment by mxcl** [comment]
@jhheider something is wrong with our lamda? This is the second report of error with this.

**Comment by mxcl** [comment]
you need the `-L` flag: 

```
curl -L https://tea.xyz/$(uname)/$(uname -m) -o tea
```

**Comment by jhheider** [comment]
I believe it's because the binary is too big to return from a lambda, so we redirect to its URL. We might be able to handle the mapping in CloudFront...

**Comment by mxcl** [comment]
is the lamba necessary? Seems like we can just put the files in the S3 bucket at these paths.

**Comment by balupton** [comment]
Ahhh, so my issue was that I wanted to see the url, then I went to it in my browser:

https://tea.xyz/Darwin/arm64

Which does 404:

image


So then I tried it via curl to find out what was going on, and got that.

I also tried the curl option, but didn't want to do the `-o` flag but forgot to remove the `tea` part, so ended up with:

```
> curl -L tea "https://tea.xyz/$(uname)/$(uname -m)"
curl: (6) Could not resolve host: tea
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
```

**Comment by jhheider** [comment]
> is the lamba necessary? Seems like we can just put the files in the S3 bucket at these paths.

this is "fixed" now:
```shell
% curl -I https://tea.xyz/Darwin/arm64
HTTP/2 200 
content-type: binary/octet-stream
content-length: 89986588
x-amz-id-2: oYHgE6j8BW9CvZp/MDecJxbPjeJ+gGbeD78+7msObcsTkdKl+5Be1b1Cu2cai0gMW4G7s5+lCI0=
x-amz-request-id: 4CQ35X27N9PV34NT
date: Thu, 27 Jul 2023 17:23:57 GMT
cache-control: no-cache,must-revalidate
last-modified: Thu, 27 Jul 2023 16:56:49 GMT
etag: "95dee9d859e631e9075d3326f31e6494-11"
server: AmazonS3
x-cache: Miss from cloudfront
via: 1.1 36f69319ab81a6da1ac84a7a4ff92ace.cloudfront.net (CloudFront)
x-amz-cf-pop: BOS50-P1
x-amz-cf-id: z38lVkv6XqBzFJNcvfkq1svTCH-VJb3t_JWBeeUqWo7v_vATQLc2aw==
vary: Origin
```

**Pull request closed without merging**
